#!/usr/bin/env bash

# Define tasks to be done on power related activity.

# kill brave
pkill --full '/opt/brave.com/brave/brave --disable-lcd-text'
sleep 1

# upload notes to remote repo
notes-auto-sync push

exit 0
